"""urun aranabilir parametreleri

Revision ID: 254add4c7164
Revises: 2bd390383d15
Create Date: 2026-08-21 16:56:52.235432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254add4c7164'
down_revision: Union[str, Sequence[str], None] = '2bd390383d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cross_section', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('products', sa.Column('core_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('conductor', sa.String(), nullable=True))
    op.add_column('products', sa.Column('insulation', sa.String(), nullable=True))
    op.add_column('products', sa.Column('sheathed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_core_count'), 'products', ['core_count'], unique=False)
    op.create_index(op.f('ix_products_cross_section'), 'products', ['cross_section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_cross_section'), table_name='products')
    op.drop_index(op.f('ix_products_core_count'), table_name='products')
    op.drop_column('products', 'sheathed')
    op.drop_column('products', 'insulation')
    op.drop_column('products', 'conductor')
    op.drop_column('products', 'core_count')
    op.drop_column('products', 'cross_section')
    # ### end Alembic commands ###
