"""teklif motoru tablolari

Revision ID: 2bd390383d15
Revises: a096f2c15539
Create Date: 2026-08-21 15:34:21.161509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd390383d15'
down_revision: Union[str, Sequence[str], None] = 'a096f2c15539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('labor_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('adjustment_template', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_quote_defaults_id'), 'quote_defaults', ['id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_quote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['parent_quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'number', 'version', name='uq_quote_no_version')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supplier_code', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discountable', sa.Boolean(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_item_id'], ['quote_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_id'), 'quote_items', ['id'], unique=False)
    op.create_table('quote_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('quote_item_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('added_discountable', sa.Boolean(), nullable=False),
    sa.Column('added_kind', sa.String(), nullable=False),
    sa.CheckConstraint('(quote_id IS NULL) <> (quote_item_id IS NULL)', name='ck_adjustment_tek_sahip'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_adjustments_id'), 'quote_adjustments', ['id'], unique=False)

    # Elle eklendi — listeleme sorguları bu kolonlardan geçiyor, autogenerate
    # yabancı anahtarlara index koymaz.
    op.create_index('ix_quotes_user_id', 'quotes', ['user_id'])
    op.create_index('ix_quotes_customer_id', 'quotes', ['customer_id'])
    op.create_index('ix_quote_items_quote_id', 'quote_items', ['quote_id'])
    op.create_index('ix_quote_adjustments_quote_id', 'quote_adjustments', ['quote_id'])
    op.create_index('ix_quote_adjustments_quote_item_id', 'quote_adjustments', ['quote_item_id'])

    # Elle eklendi — `server_default` olmadan bu üç ALTER dolu tabloda patlar:
    # mevcut satırların NOT NULL kolonu boş kalır. SQLAlchemy'deki `default=` yalnızca
    # Python tarafında çalışır, DB'ye yansımaz.
    op.add_column(
        'customers',
        sa.Column('default_adjustments', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.add_column(
        'products',
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='TRY'),
    )
    op.add_column('products', sa.Column('supplier_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'supplier_code')
    op.drop_column('products', 'currency')
    op.drop_column('customers', 'default_adjustments')
    op.drop_index('ix_quote_adjustments_quote_item_id', table_name='quote_adjustments')
    op.drop_index('ix_quote_adjustments_quote_id', table_name='quote_adjustments')
    op.drop_index('ix_quote_items_quote_id', table_name='quote_items')
    op.drop_index('ix_quotes_customer_id', table_name='quotes')
    op.drop_index('ix_quotes_user_id', table_name='quotes')
    op.drop_index(op.f('ix_quote_adjustments_id'), table_name='quote_adjustments')
    op.drop_table('quote_adjustments')
    op.drop_index(op.f('ix_quote_items_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_quote_defaults_id'), table_name='quote_defaults')
    op.drop_table('quote_defaults')
    # ### end Alembic commands ###
