"""create_catalog_tables

Revision ID: 47661d7ab065
Revises: 793690394e9f
Create Date: 2026-06-18 13:16:40.713117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47661d7ab065'
down_revision: Union[str, Sequence[str], None] = '793690394e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('technical_specs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'technical_specs')
    # ### end Alembic commands ###
